version: '3'

volumes:
  images:
  db:
  supervisorlog:
  redis-data:

networks:
  blog1997:

services:
  redis:
    image: chaosxy/redis
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - blog1997
    command: --requirepass ${redis_password:-masterauth}
  db:
    image: mysql:5.7.29
    command: --ngram_token_size=1
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${db_password:-admin123}
      - MYSQL_PASSWORD=${db_password:-admin123}
      - MYSQL_USER=${db_username:-xy}
      - MYSQL_DATABASE=${db_name}
    networks:
      - blog1997
  # laravel
  php:
    tty: true
    image: chaosxy/blog1997-api:1.0.1
    links:
      - db
    networks:
      - blog1997
    ports:
      - 9000:9000
    volumes:
      - images:/var/www/storage/image/
      - supervisorlog:/var/log/supervisor/
      - ./config/php.ini:/usr/local/etc/php/php.ini
    environment:
      - MASTER_EMAIL=${email:-admin@qq.com}
      - APP_KEY=${app_key}
      - DB_USERNAME=${db_username:-xy}
      - APP_URL=${domain:-http://localhost}
      - REDIS_PASSWORD=${redis_password:-masterauth}
      - MAIL_HOST=${mail_host}
      - MAIL_USERNAME=${mail_username}
      - MAIL_PASSWORD=${mail_password}
      - DB_PASSWORD=${db_password:-admin123}
      - WECHAT_APP_ID=${wechat_app_id}
      - WECHAT_SECRET=${wechat_secret}
      - GIT_CLIENT_ID=${git_client_id}
      - GIT_SECRET=${git_secret}
      - WECHAT_PUBLIC_APP_ID=${wechat_public_app_id}
      - WECHAT_PUBLIC_SECRET=${wechat_public_secret}
      - GMAP_KEY=${gamp_key}
  # ssr前端
  nuxt:
    image: chaosxy/blog1997:1.0.4
    tty: true
    ports:
      - 3000:3000
    networks:
      - blog1997
    environment:
      - TITLE="${title:-blog1997}"
      - API_URL="${api_url:-http://localhost/api}"
      - WECHAT_APP_ID="${wechat_app_id}"
      - GIT_CLIENT_ID="${git_client_id}"
      - DESCRIPTION="${description}"
      - BEIAN="${beian}"
      - ANALYTICS="${analytics}"
  nginx:
    image: chaosxy/blog1997-nginx:1.0.2
    networks:
      - blog1997
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./config/blog1997.crt:/etc/ssl/certs/blog1997.crt:r
      # - ./config/blog1997.key:/etc/ssl/certs/blog1997.key:r
    environment:
      - TITLE="${title:-blog1997}"
      - API_URL="${api_url:-http://localhost/api}"
      - WECHAT_APP_ID="${wechat_app_id}"
      - GIT_CLIENT_ID="${git_client_id}"
      - DOMAIN="${domain:-localhost}"
      - GMAP_KEY=${gamp_key}
