version: '3.9'

volumes:
  mysql-vol:
    external: true
  supervisorlog:
  redis-data:

networks:
  blog1997:
    driver: overlay
    attachable: true

configs:
  redis-config:
    file: ./config/redis.conf
  php-config:
    file: ./config/php.ini
  php-fpm-config:
    file: ./config/php-fpm.conf

services:
  redis:
    image: chaosxy/redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    configs:
      - source: redis-config
        target: /etc/redis/redis.conf
        mode: 0444
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.region==tencent"
    networks:
      - blog1997
    command: --requirepass blog1997-redis
  db:
    image: mysql:5.7.29
    command: --ngram_token_size=1 --ft_min_word_len=1
    ports:
      - 3306:3306
    deploy:
      replicas: 1
      placement:
        # constraints:
        #   - "node.labels.region=="
    volumes:
      - mysql-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_USER=blog1997
      - MYSQL_DATABASE=blog1997
    networks:
      - blog1997
  # laravel
  php:
    tty: true
    image: chaosxy/blog1997-api:1.0.1
    networks:
      - blog1997
    deploy:
      replicas: 1
      placement:
        # constraints:
        #   - "node.labels.region=="
    volumes:
      - supervisorlog:/var/log/supervisor/
      - /var/www/images/:/var/www/storage/image/:rw
    configs:
      - source: php-config
        target: /usr/local/etc/php/php.ini
        mode: 0444
      - source: php-fpm-config
        target: /usr/local/etc/php-fpm.d/www.conf
        mode: 0444
    environment:
      - MASTER_EMAIL=cdk.1997@outlook.com
      - APP_KEY=
      - DB_USERNAME=
      - APP_URL=
      - REDIS_PASSWORD=
      - MAIL_HOST=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - DB_PASSWORD=
      - WECHAT_APP_ID=
      - WECHAT_SECRET=
      - GIT_CLIENT_ID=
      - GIT_SECRET=
      - WECHAT_PUBLIC_APP_ID=
      - WECHAT_PUBLIC_SECRET=
      - GMAP_KEY=
      - MAIL_PORT=465
      - DB_DATABASE=xy_blog1997
  # ssr前端
  nuxt:
    image: chaosxy/blog1997:1.0.4
    tty: true
    networks:
      - blog1997
    deploy:
      replicas: 1
      placement:
        # constraints:
        #   - "node.labels.region=="
    environment:
      - TITLE="Blog1997"
      - API_URL=""
      - WEICHAT_APP_ID=""
      - GIT_CLIENT_ID=""
      - DESCRIPTION=""
      - BEIAN=""
      - ANALYTICS=""
      - DOMAIN=""
  nginx:
    image: chaosxy/blog1997-nginx:1.0.2
    networks:
      - blog1997
    deploy:
      replicas: 1
      placement:
        # constraints:
        #   - "node.labels.region=="
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        delay: 10s
    ports:
      - 80:80
    configs:
      - source: nginx-server-conf
        target: /etc/nginx/conf.d/default.conf
      - source: nginx-conf
        target: /etc/nginx/nginx.conf
    environment:
      - TITLE="Blog1997"
      - API_URL=""
      - WECHAT_APP_ID=""
      - GIT_CLIENT_ID=""
      - DOMAIN=""
      - GMAP_KEY=""